### ISSUE TITLE
Not working in 1.18.2

### ISSUE THREAD

**Issue by Moon-developer** [Arthed-Plugins/Crawling#10]
Getting this in the console log:
```
Server thread/ERROR17:10:15
An error occurred while enabling Crawling v5.2.1 (Is it up to date?)
```
Currently on 1.18.2

**Comment by Nononitas** [comment]
For me too. 
Error on startup https://pastebin.com/tRcjbsYY

**Comment by iBELLinc** [comment]
This is also happening for me. Here is the console output:
<details>
<summary>Console Output</summary>

[03:40:10] [Server thread/ERROR]: Error occurred while enabling Crawling v5.2.1 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R1/entity/CraftEntity
        at me.arthed.crawling.nms.v1_18.NmsPackets_v1_18.<init>(NmsPackets_v1_18.java:34) ~[?:?]
        at me.arthed.crawling.Crawling.onEnable(Crawling.java:67) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:518) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3494-Spigot-b081915-9d46b56]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:432) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3494-Spigot-b081915-9d46b56]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3494-Spigot-b081915-9d46b56]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3494-Spigot-b081915-9d46b56]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:263) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3494-Spigot-b081915-9d46b56]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1007) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3494-Spigot-b081915-9d46b56]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3494-Spigot-b081915-9d46b56]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.entity.CraftEntity
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 13 more
</details>

I attempted to use the temporary file [here](https://github.com/TheNickm2/Crawling/releases/tag/5.2.0) from a previous bug report and it does appear to be working in 1.18.2.
